name: using_the_movie_db_api
version: 1.0.0+1
description: A new Flutter module project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  dio: ^4.0.6
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  module: 
    androidPackage: com.example.using_the_movie_db_api
    iosBundleIdentifier: com.example.usingTheMovieDbApi
    androidX: true
  uses-material-design: true

